// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoiCcrYKxmVPfRXW00ZzofH0Xq7ifFfXA',
    appId: '1:174376549785:web:069e265dc1887edc2ae708',
    messagingSenderId: '174376549785',
    projectId: 'habit-374505',
    authDomain: 'habit-374505.firebaseapp.com',
    storageBucket: 'habit-374505.appspot.com',
    measurementId: 'G-0CVHKBY648',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQXapomtcjBRGhulcDe-MXeCfXtoEg2d8',
    appId: '1:174376549785:android:f5973afaef71e6602ae708',
    messagingSenderId: '174376549785',
    projectId: 'habit-374505',
    storageBucket: 'habit-374505.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnYZuT4HLMT3Dv1sRzEC7z1pmBkr0BbA4',
    appId: '1:174376549785:ios:7058e477ea8a2afc2ae708',
    messagingSenderId: '174376549785',
    projectId: 'habit-374505',
    storageBucket: 'habit-374505.appspot.com',
    androidClientId: '174376549785-c0hgghvp9429tu4oagvcklofp57qh9ji.apps.googleusercontent.com',
    iosClientId: '174376549785-4ti6crfm73upqeemf2nh279hbjtn0i7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitTrackerPlp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnYZuT4HLMT3Dv1sRzEC7z1pmBkr0BbA4',
    appId: '1:174376549785:ios:7058e477ea8a2afc2ae708',
    messagingSenderId: '174376549785',
    projectId: 'habit-374505',
    storageBucket: 'habit-374505.appspot.com',
    androidClientId: '174376549785-c0hgghvp9429tu4oagvcklofp57qh9ji.apps.googleusercontent.com',
    iosClientId: '174376549785-4ti6crfm73upqeemf2nh279hbjtn0i7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitTrackerPlp',
  );
}
