// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeIPzGp-q-eZo-JJOkmebg_VJVWGJaMQM',
    appId: '1:1081085881894:web:61ff2ef9d6951fa9a0c0e7',
    messagingSenderId: '1081085881894',
    projectId: 'plp-dart-bootcamp-project',
    authDomain: 'plp-dart-bootcamp-project.firebaseapp.com',
    storageBucket: 'plp-dart-bootcamp-project.appspot.com',
    measurementId: 'G-LBDLNXBRF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUrU8VvGY553SHCrFooe-9av6ygok1tww',
    appId: '1:1081085881894:android:5cd45a5f90239e20a0c0e7',
    messagingSenderId: '1081085881894',
    projectId: 'plp-dart-bootcamp-project',
    storageBucket: 'plp-dart-bootcamp-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcO_m0YznrAXQQzBPR-zJB77y48LORWrM',
    appId: '1:1081085881894:ios:7778ddaac602bb1ba0c0e7',
    messagingSenderId: '1081085881894',
    projectId: 'plp-dart-bootcamp-project',
    storageBucket: 'plp-dart-bootcamp-project.appspot.com',
    iosClientId: '1081085881894-gfaion9ffv8gaf9tlss3cpaiumtmf7bf.apps.googleusercontent.com',
    iosBundleId: 'com.adeelsafdar.loginsignup.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcO_m0YznrAXQQzBPR-zJB77y48LORWrM',
    appId: '1:1081085881894:ios:7778ddaac602bb1ba0c0e7',
    messagingSenderId: '1081085881894',
    projectId: 'plp-dart-bootcamp-project',
    storageBucket: 'plp-dart-bootcamp-project.appspot.com',
    iosClientId: '1081085881894-gfaion9ffv8gaf9tlss3cpaiumtmf7bf.apps.googleusercontent.com',
    iosBundleId: 'com.adeelsafdar.loginsignup.loginSignup',
  );
}
